### ISSUE TITLE
Naslov v datoteki README

### ISSUE THREAD

**Issue by katjabercic** [Roadman3D/racunalniski-praktikum#1]
V README.md datoteki v prvi vrstici piše `# Racunalniski praktikum`, moralo bi pisati `# Računalniški praktikum`. Če popravite, boste dobili točko.

Lep pozdrav,
Katja

**Comment by Roadman3D** [comment]
Hvala, ker ste opazili tipkarsko napako in me obvestili. Popravil sem jo + dodal dodatno besedilo, ki smo ga napisali na danasnjem rac praktikume.

Najlepsa hvala,
Roman Mareev
